apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes: # Define volume
        - name: shared-string
          emptyDir: {}
      containers:
        - name: log-output-app
          image: meqdad0/log-output-k8:latest
          volumeMounts: # Mount volume
          - name: shared-string
            mountPath: /usr/src/app/files
        - name: log-output-reader
          image: meqdad0/hash-reader-k8:latest
          volumeMounts: # Mount volume
          - name: shared-string
            mountPath: /usr/src/app/files
